import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { logger } from '../lib/logger.js';
import { githubApi } from '../lib/github-api.js';
import type { Task, AutoissueConfig } from '../lib/types.js';

const execFileAsync = promisify(execFile);

/**
 * Task metrics from git diff.
 */
export interface TaskMetrics {
  linesAdded: number;
  linesRemoved: number;
  filesChanged: number;
}

/**
 * Create a pull request for a completed task.
 *
 * Uses @octokit/rest for 10x performance improvement over gh CLI.
 *
 * @param task - The completed task
 * @param branch - Branch name
 * @param config - Autoissue configuration
 * @returns PR number
 */
export async function createPullRequest(
  task: Task,
  branch: string,
  config: AutoissueConfig,
  worktreePath: string
): Promise<number> {
  logger.debug('Creating PR via Octokit', { issueNumber: task.issueNumber, branch });

  try {
    // Push branch to remote before creating PR
    logger.debug('Pushing branch to remote', { branch, worktreePath });
    await execFileAsync('git', ['push', '-u', 'origin', branch], { cwd: worktreePath });
    logger.info('Branch pushed to remote', { branch });

    // Build PR title and body
    const title = `${task.title}`;
    const body = `Closes #${task.issueNumber}

${task.body}

---
🤖 Generated by Autoissue`;

    // Create PR via Octokit (10x faster than gh CLI)
    const prNumber = await githubApi.createPullRequest(
      config.project.repo,
      config.project.baseBranch,
      branch,
      title,
      body,
      config.executor.prDraft
    );

    logger.info('PR created via Octokit', {
      issueNumber: task.issueNumber,
      prNumber,
      branch,
      draft: config.executor.prDraft,
    });

    return prNumber;
  } catch (err) {
    logger.error('Failed to create PR', {
      issueNumber: task.issueNumber,
      branch,
      error: err instanceof Error ? err.message : String(err),
    });
    throw new Error(`Failed to create PR: ${err instanceof Error ? err.message : String(err)}`);
  }
}

/**
 * Gather task metrics from git diff.
 *
 * @param worktreePath - Path to the worktree
 * @returns Task metrics (lines added/removed, files changed)
 */
export async function gatherTaskMetrics(worktreePath: string): Promise<TaskMetrics> {
  try {
    const { stdout } = await execFileAsync('git', [
      'diff', '--shortstat', 'HEAD~1', 'HEAD'
    ], { cwd: worktreePath });

    const match = stdout.match(/(\d+) files? changed(?:, (\d+) insertions?\(\+\))?(?:, (\d+) deletions?\(-\))?/);

    return {
      filesChanged: parseInt(match?.[1] || '0', 10),
      linesAdded: parseInt(match?.[2] || '0', 10),
      linesRemoved: parseInt(match?.[3] || '0', 10),
    };
  } catch (err) {
    logger.warn('Failed to gather task metrics', {
      worktreePath,
      error: err instanceof Error ? err.message : String(err),
    });

    // Return zeros if metrics gathering fails
    return {
      filesChanged: 0,
      linesAdded: 0,
      linesRemoved: 0,
    };
  }
}

/**
 * Update PR with additional information (e.g., metrics, test results).
 *
 * Uses @octokit/rest for better performance and type safety.
 *
 * @param prNumber - PR number
 * @param repo - Repository (owner/repo)
 * @param additionalInfo - Information to append to PR body
 */
export async function updatePullRequest(
  prNumber: number,
  repo: string,
  additionalInfo: string
): Promise<void> {
  logger.debug('Updating PR via Octokit', { prNumber, repo });

  try {
    // Add comment with additional info instead of updating PR body
    // (simpler and doesn't require fetching current body)
    await githubApi.createComment(prNumber, repo, additionalInfo);

    logger.info('PR updated with comment via Octokit', { prNumber });
  } catch (err) {
    logger.error('Failed to update PR', {
      prNumber,
      error: err instanceof Error ? err.message : String(err),
    });
  }
}

/**
 * Format task metrics as markdown for PR comments.
 *
 * @param metrics - Task metrics
 * @returns Formatted markdown string
 */
export function formatMetrics(metrics: TaskMetrics): string {
  return `## 📊 Changes
- **Files changed:** ${metrics.filesChanged}
- **Lines added:** +${metrics.linesAdded}
- **Lines removed:** -${metrics.linesRemoved}
- **Net change:** ${metrics.linesAdded - metrics.linesRemoved > 0 ? '+' : ''}${metrics.linesAdded - metrics.linesRemoved}`;
}
